name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.REPO_SCOPE }}
        with:
          path-to-signatures: 'signatures.json'
          path-to-document: 'https://github.com/BloodHoundAD/CLA/blob/main/ICLA.md'
          branch: 'main'
          remote-organization-name: BloodHoundAD
          remote-repository-name:  CLA
