name: Publish

on:
  push: 
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        release:
          - type: Debug
            suffix: '-debug'
          - type: Release
            suffix: ''

    name: Build (${{ matrix.release.type }})

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: |
          VERSION=${{ github.ref_name }}
          dotnet build -c ${{ matrix.release.type }} -p:Version=${VERSION:1}

      - name: Zip
        run: 7z a -tzip -mx9 SharpHound-${{ github.ref_name }}${{ matrix.release.suffix }}.zip $PWD/bin/${{ matrix.release.type }}/net462/*

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: SharpHound-${{ github.ref_name }}${{ matrix.release.suffix }}.zip
