[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayPythonByExtension"
MatchAction = "Relay"
RelayTargets = ["KeepPyDbConnStrings",
"KeepAwsKeysInCode",
"KeepInlinePrivateKey",
"KeepPassOrKeyInCode",  "KeepSlackTokensInCode",
"KeepSqlAccountCreation",
"KeepDbConnStringPw" ]
Description = "Files with these extensions will be searched for python related strings."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.py"]
Triage = "Green"