[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayRubyByExtension"
MatchAction = "Relay"
RelayTargets = ["KeepRubyDbConnStrings",
"KeepAwsKeysInCode",
"KeepInlinePrivateKey",
"KeepPassOrKeyInCode",  "KeepSlackTokensInCode",
"KeepSqlAccountCreation",
"KeepDbConnStringPw" ]
Description = "Files with these extensions will be searched for Rubby related strings."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.rb"]
Triage = "Green"