[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepFtpServerConfigByName"
MatchAction = "Snaffle"
Description = "Files with these exact names are very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = ["proftpdpasswd",
"filezilla\\.xml"]
Triage = "Red"