[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepKerberosCredentialsByExtension"
MatchAction = "Snaffle"
Description = "Files with these extensions are interesting."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = [
"\\.keytab",
"\\.CCACHE"]
Triage = "Yellow"