[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepKerberosCredentialsByName"
MatchAction = "Snaffle"
Description = "Files with these names are interesting."
MatchLocation = "FileName"
WordListType = "Regex"
MatchLength = 0
WordList = [
"krb5cc_.*"]
Triage = "Yellow"