[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepSqlAccountCreation"
MatchAction = "Snaffle"
Description = "Files with contents matching these regexen are very interesting."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["CREATE (USER|LOGIN) .{0,200} (IDENTIFIED BY|WITH PASSWORD)"]
Triage = "Red"