[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepSCCMBootVarCredsByPath"
MatchAction = "Snaffle"
Description = "Files with a path containing these strings are very interesting."
MatchLocation = "FilePath"
WordListType = "Regex"
MatchLength = 0
WordList = ["REMINST\\\\SMSTemp\\\\.*\\.var",
			"SMS\\\\data\\\\Variables.dat",
			"SMS\\\\data\\\\Policy.xml"
		]
Triage = "Red"