[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepDefenderConfigByName"
MatchAction = "Snaffle"
Description = "Files containing Defender Configs are very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = ["SensorConfiguration.json"]
Triage = "Yellow"
