[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayConfigByExtension"
MatchAction = "Relay"
RelayTargets = [
"KeepAwsKeysInCode",
"KeepInlinePrivateKey",
"KeepPassOrKeyInCode",  
"KeepSlackTokensInCode",
"KeepSqlAccountCreation",
"KeepDbConnStringPw"]
Description = "Files with these extensions will be subjected to a generic search for keys and such."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.yaml",
"\\.yml",
"\\.toml",
"\\.xml",
"\\.json",
"\\.config",
"\\.ini",
"\\.inf",
"\\.cnf",
"\\.conf",
"\\.properties",
"\\.env",
"\\.dist",
"\\.txt",
"\\.sql",
"\\.log",
"\\.sqlite",
"\\.sqlite3",
"\\.fdb",
"\\.tfvars"]
Triage = "Green"