[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepCloudApiKeysByPath"
MatchAction = "Snaffle"
Description = "Files with a path containing these strings are very very interesting."
MatchLocation = "FilePath"
WordListType = "Contains"
MatchLength = 0
WordList = ["\\\\\\.aws\\\\",
"doctl\\\\config.yaml"]
Triage = "Black"