name: aicoder

on:
  workflow_dispatch:

jobs:
  Build_and_test_winpeas_master:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: AICoder GH Action
        uses: AICoderHub/GH_Action@v0.11
        with:
          INPUT_MODE: 'file-optimizer'
          INPUT_PROMPT: ''
          INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INPUT_MODEL: 'gpt-4'
          TEMPLATE_FILES: ''
          ORIGIN_BRANCH: 'aicoder'
          TO_BRANCH: 'master'
          CHECK_PATH: './parsers/json2pdf.py'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
