[[ClassifierRules]]
EnumerationScope = "ShareEnumeration"
RuleName = "DiscardNonFileShares"
MatchAction = "Discard"
Description = "Skips scanning inside shares ending with these words."
MatchLocation = "ShareName"
WordListType = "EndsWith"
MatchLength = 0
WordList = ["\\\\print\\$",
"\\\\ipc\\$"]
Triage = "Green"