[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepCmdCredentials"
MatchAction = "Snaffle"
Description = "Files with contents matching these regexen are very interesting."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["passwo?r?d\\s*=\\s*[\\'\\\"][^\\'\\\"]....",
"schtasks.{1,300}(/rp\\s|/p\\s)",
"net user ",
"psexec .{0,100} -p ",
"net use .{0,300} /user:",
"cmdkey "
]
Triage = "Red"