[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepShellRcFilesByName"
MatchAction = "Snaffle"
Description = "Files with these exact names are very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.netrc",
"_netrc",
"\\.exports",
"\\.functions",
"\\.extra",
"\\.npmrc",
"\\.env",
"\\.bashrc",
"\\.profile",
"\\.zshrc"]
Triage = "Green"
